//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TastoDestro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TastoDestro.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R0lGODlhGAAYAPcAAAAAAA1qPhVwOiJ7Pyh7Og9rRSZ6QSlyTTJrSjFpTTZtUjB2UzxzVz1yWEd9X0p8YzKBOTaDOTiFOTmGSjuOTUWMOFeXOFChPFmmPmagOGSuPkyGSEiPX1mZQ0aNYEmgUVynS12nT1GrWly4ZWKOeGaQeWiSeWuVemyWemqdfnGZe3Wce3adfGauQWeuSWuyQGqwSX2uT3O3RXa6QXi7Q36+QnywX3u7VGqubWSge2ShfGOwYmS5aGmwYnqhfnuven23cWvDcW3Gc2/IdXnDeHrHfXnJfGyUgGqdg3WbiHmliH2sgHmxgoC5RoO+RYG/VYLBQ4bEQ4nFRYjESY/JRY/JS4rFVJTNRofAZY/GYYvAeZzMdoyxjoq/g4ixlYu0lpm/mZetopC2o521qIHMhYbOiYvAhY/ChYrAjo3CkYzQj5HKipfJjJnBiZLCkJHDlJXEkZfIm5vAmZrAm5zBmZ7CmpzKnpLSlZrBsKDDl6DDmqHE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ICONAEXCEL {
            get {
                return ResourceManager.GetString("ICONAEXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABmJLR0QA/wD/AP+gvaeTAAAgAElEQVR4nO3d95cdZ37n98/Nfbv7ds45oIFGzomZHHLI4Qwnj0bR65V8tNnnaO211v+A/YO99q6tWclayUqjkSxpEodhOOQwAARIkCBy6Aa60eicc7zZP0DkggEEcKvurapb79c5/IVEPfVl4/atT1U9z/P1CB8zNTWwJ5Xy/orHk35YUsM//lNgcVkA7G1d0pjHozck71/W1LQct7og4G48VhdgF9PTN7+cSul/kbTL6loAOFsqlX45vrr0P7Vs2n3J6lqAO3F9ALh+/XooEgn8Z49Hv211LQDyQzKZ0OryQjwQCj3W1rbzpNX1AJ/Fa3UBVhoeHg6XlgZe5uIPwGypVCoQj0bfunnz4gNW1wJ8FtcGgHQ67QkGk99Pp/W41bUAyE+pVMpPCIBduTYATE8P/WtJ37S6DgD5jRAAu3LlHICpqYG6dNrT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ICONAJSON {
            get {
                return ResourceManager.GetString("ICONAJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  STUFF(( SELECT &apos;,&apos; + quotename(a.COLUMN_NAME) FROM INFORMATION_SCHEMA.COLUMNS a WHERE TABLE_NAME = &apos;{0}&apos; FOR XML PATH(&apos;&apos;)), 1, 1, &apos;&apos;).
        /// </summary>
        internal static string SQLCOLONNE {
            get {
                return ResourceManager.GetString("SQLCOLONNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  STUFF(( SELECT &apos;,&apos; + quotename(a.COLUMN_NAME) FROM INFORMATION_SCHEMA.COLUMNS a WHERE TABLE_NAME = &apos;{0}&apos; FOR XML PATH(&apos;&apos;)), 1, 1, &apos;&apos;);
        ///SELECT CASE OBJECTPROPERTY(OBJECT_ID(&apos;{0}&apos;), &apos;TableHasIdentity&apos;)WHEN 1 THEN &apos;1&apos; ELSE &apos;0&apos; END;
        ///SELECT * FROM [{1}].[{0}];
        ///SELECT a.COLUMN_NAME as NOMECOLONNA,a.DATA_TYPE TIPOCOLONNA FROM INFORMATION_SCHEMA.COLUMNS a WHERE TABLE_NAME = &apos;{0}&apos;;.
        /// </summary>
        internal static string SQLCOMPLETA {
            get {
                return ResourceManager.GetString("SQLCOMPLETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CASE OBJECTPROPERTY(OBJECT_ID(&apos;{0}&apos;), &apos;TableHasIdentity&apos;)WHEN 1 THEN &apos;1&apos; ELSE &apos;0&apos; END.
        /// </summary>
        internal static string SQLIDENTITTY {
            get {
                return ResourceManager.GetString("SQLIDENTITTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [{0}].[{1}].
        /// </summary>
        internal static string SQLSELECT {
            get {
                return ResourceManager.GetString("SQLSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.COLUMN_NAME as NOMECOLONNA,a.DATA_TYPE TIPOCOLONNA FROM INFORMATION_SCHEMA.COLUMNS a WHERE TABLE_NAME = &apos;{0}&apos;.
        /// </summary>
        internal static string SQLTIPICOLONNE {
            get {
                return ResourceManager.GetString("SQLTIPICOLONNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^Server\[[^\]]*\]/Database\[[^\]]*\]/Table\[[^\]]*\]$.
        /// </summary>
        internal static string TableRegEx {
            get {
                return ResourceManager.GetString("TableRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([A-Z])\w+.
        /// </summary>
        internal static string TableRegEx2 {
            get {
                return ResourceManager.GetString("TableRegEx2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \[[^\]]*\]*.&apos;*.&apos;*.\[*.\].
        /// </summary>
        internal static string TableRegEx3 {
            get {
                return ResourceManager.GetString("TableRegEx3", resourceCulture);
            }
        }
    }
}
